create or replace package body test_cdc_guidance is

   /* generated by utplsql for sql developer on 2022-03-10 10:22:13 */

   --
   -- test quarantine_isolation_guidance   --
   procedure days_to_separate_scenario1 is
      l_actual           integer := 0;
      l_expected         integer := 5;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => true, 
                                p_exposed            => true,
                                p_able_to_mask       => true,
                                p_vaccine_up_to_date => true
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario1;
   
   procedure days_to_separate_scenario2 is
      l_actual           integer := 0;
      l_expected         integer := 0;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => false, 
                                p_exposed            => true,
                                p_able_to_mask       => true,
                                p_vaccine_up_to_date => true
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario2;
   
   procedure days_to_separate_scenario3 is
      l_actual           integer := 0;
      l_expected         integer := 5;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => true, 
                                p_exposed            => false,
                                p_able_to_mask       => true,
                                p_vaccine_up_to_date => true
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario3;
   
   procedure days_to_separate_scenario4 is
      l_actual           integer := 0;
      l_expected         integer := 10;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => true, 
                                p_exposed            => true,
                                p_able_to_mask       => false,
                                p_vaccine_up_to_date => true
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario4;
   
   procedure days_to_separate_scenario5 is
      l_actual           integer := 0;
      l_expected         integer := 5;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => true, 
                                p_exposed            => true,
                                p_able_to_mask       => true,
                                p_vaccine_up_to_date => false
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario5;
   
   procedure days_to_separate_scenario6 is
      l_actual           integer := 0;
      l_expected         integer := 0;
      l_days_to_separate number;
   begin
      -- populate actual
      -- cdc_guidance.quarantine_isolation_guidance;
      l_actual := cdc_guidance.days_to_separate(
                                p_tested_positive    => false, 
                                p_exposed            => false,
                                p_able_to_mask       => true,
                                p_vaccine_up_to_date => true
                                );

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end days_to_separate_scenario6;

end test_cdc_guidance;
/